# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8479d72db311aef992868d6a50f83947f02050c8a3fb71654dcb5f3a892408ba89133221ed2a2daead850091e7554332e5926506ab84c2da60659ab366701441

test:
  secret_key_base: cd4fd2aa146dc68fa57c74c6ade1c74c599548200cacbbef2c225cc083d399c4b431a422024f911cb80715e5a5e2f39c9c76239765bd8cc362e047fc99f68a04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
